{% set name = "gnuradio-radar" %}
{% set hash = "7a49711067fc3ad80dae4fe202937088ab2bff17" %}
{% set version = "0.0.20200129" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  #url: https://github.com/primercuervo/gr-radar/archive/v{{ version }}.tar.gz
  #sha256:
  git_url: https://github.com/primercuervo/gr-radar.git
  git_rev: {{ hash }}
  patches:
    - 0001-Replace-not-with-for-MSVC-compatibility.patch
    - 0002-M_PI-GR_M_PI-to-match-gnuradio-and-have-MSVC-compati.patch
    - 0003-Use-gr_complex-instead-of-1j-for-non-gcc-compatibili.patch
    - 0004-Do-not-link-gnuradio-radar-with-Python-not-necessary.patch

build:
  number: 0
  run_exports:
    - {{ pin_subpackage('gnuradio-radar', max_pin='x.x.x') }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - make  # [not win]
    - ninja  # [win]
    - pkg-config  # [not win]
   # below are needed to link with Qt
    - {{ cdt('libice') }}  # [linux]
    - {{ cdt('libselinux') }}  # [linux]
    - {{ cdt('libsm') }}  # [linux]
    - {{ cdt('libx11') }}  # [linux]
    - {{ cdt('libxau') }}  # [linux]
    - {{ cdt('libxcb') }}  # [linux]
    - {{ cdt('libxdamage') }}  # [linux]
    - {{ cdt('libxext') }}  # [linux]
    - {{ cdt('libxfixes') }}  # [linux]
    - {{ cdt('libxrender') }}  # [linux]
    - {{ cdt('libxxf86vm') }}  # [linux]
    - {{ cdt('libuuid') }}  # [linux]
    - {{ cdt('mesa-dri-drivers') }}  # [linux]
    - {{ cdt('mesa-libgl-devel') }}  # [linux]
  host:
    - boost-cpp
    - fftw
    - gnuradio-core
    - pip  # [win]
    - pyqt
    - python
    - qt
    - qwt
    - swig
    - uhd
    - volk
    # pulled in by gnuradio-core and linked against, so include explicitly
    - log4cpp
  run:
    - boost-cpp
    - fftw
    - pyqt
    - python
    - {{ pin_compatible('qwt', max_pin='x.x') }}
    # pulled in by gnuradio-core and linked against, so include explicitly
    - log4cpp

test:
  commands:
    # verify that (some) headers get installed
    {% set headers = [
        "api",
        "estimator_cw",
        "tracking_singletarget",
    ] %}
    {% for header in headers %}
    - test -f $PREFIX/include/radar/{{ header }}.h  # [not win]
    - if not exist %PREFIX%\\Library\\include\\radar\\{{ header }}.h exit 1  # [win]
    {% endfor %}

    # verify that libraries get installed
    - test -f $PREFIX/lib/lib{{ name }}${SHLIB_EXT}  # [not win]
    - if not exist %PREFIX%\\Library\\bin\\{{ name }}.dll exit 1  # [win]
    - if not exist %PREFIX%\\Library\\lib\\{{ name }}.lib exit 1  # [win]

    # verify that (some) GRC blocks get installed
    {% set blocks = [
        "radar_crop_matrix_vcvc",
        "radar_estimator_cw",
        "radar_find_max_peak_c",
        "radar_msg_gate",
        "radar_ofdm_cyclic_prefix_remover_cvc",
        "radar_os_cfar_2d_vc",
        "radar_print_results",
        "radar_qtgui_scatter_plot",
        "radar_signal_generator_cw_c",
        "radar_split_cc",
        "radar_static_target_simulator_cc",
        "radar_tracking_singletarget",
        "radar_transpose_matrix_vcvc",
        "radar_trigger_command",
        "radar_ts_fft_cc",
        "radar_usrp_echotimer_cc",
    ] %}
    {% for block in blocks %}
    - test -f $PREFIX/share/gnuradio/grc/blocks/{{ block }}.block.yml  # [not win]
    - if not exist %PREFIX%\\Library\\share\\gnuradio\\grc\\blocks\\{{ block }}.block.yml exit 1  # [win]
    {% endfor %}
  imports:
    - radar

about:
  home: https://github.com/primercuervo/gr-radar
  license: GPL-3.0-or-later
  license_family: GPL
  #license_file: LICENSE
  summary: 'GNU Radio Radar Toolbox'
  dev_url: https://github.com/primercuervo/gr-radar

extra:
  recipe-maintainers:
    - ryanvolz
