{% set name = "libfec" %}
{% set version = "2.1.1+20161003" %}
{% set deb_version = "1.0+20161003" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  # get tarball from Debian since the most recent Github tag is out of date
  url: 'http://deb.debian.org/debian/pool/main/libf/{{ name }}/{{ name }}_{{ deb_version }}.orig.tar.gz'
  sha256: ded8df064d501cae253e3fafe902c4405536ed9067517b213d237c47685d5868
  patches:
    - patches/sim
    - patches/soname
    - patches/compileflags

build:
  number: 0
  run_exports:
    # hard to know how they change the soversion, so be safe and pin tightly
    - {{ pin_subpackage('libfec', max_pin='x.x.x') }}

requirements:
  build:
    - {{ compiler('c') }}  # [not win]
    # upstream does not support compiling with MSVC
    - {{ compiler('m2w64_c') }}  # [win]
    - cmake
    - make  # [not win]
    - ninja  # [win]

test:
  commands:
    - test -f $PREFIX/include/fec.h   # [unix]
    - test -f $PREFIX/lib/libfec${SHLIB_EXT}  # [unix]
    - if not exist %PREFIX%\\Library\\bin\\libfec.dll exit 1  # [win]
    - if not exist %PREFIX%\\Library\\lib\\libfec.dll.a exit 1  # [win]
    - if not exist %PREFIX%\\Library\\lib\\libfec.lib exit 1  # [win]

about:
  home: https://github.com/quiet/libfec
  license: LGPL-2.1-or-later
  license_file: lesser.txt
  summary: 'Forward error correction (FEC) algorithms'
  description: |
    This package provides a set of functions that implement several popular
    forward error correction (FEC) algorithms and several low-level routines
    useful in modems implemented with digital signal processing (DSP).
  dev_url: https://github.com/quiet/libfec

extra:
  recipe-maintainers:
    - petrushy
    - ryanvolz
