{% set name = "libcorrect" %}
{% set version = "0+20181010" %}
{% set git_hash = "f5a28c74fba7a99736fe49d3a5243eca29517ae9" %}
{% set hash = "75e326fb37d6d724e2a4da2433d6a2eb46f084a312ea0d864ac3a19fbe7c9409" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/quiet/{{ name }}/archive/{{ git_hash }}.zip
  sha256: {{ hash }}

build:
  number: 0
  run_exports:
    - {{ pin_subpackage('libcorrect') }}

requirements:
  build:
    - {{ compiler('c') }}
    - cmake
    - make  # [unix]

test:
  commands:
    # check that headers get installed
    - test -f $PREFIX/include/correct.h  # [unix]
    - test -f $PREFIX/include/correct-sse.h   # [unix]
    - test -f $PREFIX/include/fec.h  # [unix]
    - if not exist %PREFIX%\\Library\\include\\correct.h exit 1  # [win]
    - if not exist %PREFIX%\\Library\\include\\fec.h exit 1  # [win]

    # check that libraries get installed
    - test -f $PREFIX/lib/libcorrect${SHLIB_EXT}  # [unix]
    - test -f $PREFIX/lib/libcorrect.a  # [unix]
    - test -f $PREFIX/lib/libfec${SHLIB_EXT}  # [unix]
    - test -f $PREFIX/lib/libfec.a  # [unix]
    - if not exist %PREFIX%\\Library\\lib\\correct.dll exit 1  # [win]
    - if not exist %PREFIX%\\Library\\lib\\correct.lib exit 1  # [win]
    - if not exist %PREFIX%\\Library\\lib\\fec.dll exit 1  # [win]
    - if not exist %PREFIX%\\Library\\lib\\fec.lib exit 1  # [win]

about:
  home: https://github.com/quiet/libcorrect
  license: BSD-3-Clause
  license_file: LICENSE
  summary: 'A library for Forward Error Correction'
  description: |
    libcorrect is a library for Forward Error Correction. By using libcorrect,
    you can encode extra redundancy into a packet of data and then send it
    across a lossy channel. When the packet is received, it can be decoded to
    recover the original, pre-encoded data.

    libcorrect accomplishes this task with two algorithms, Convolutional codes
    and Reed-Solomon. Convolutional codes are robust to a constant background
    noise, while Reed-Solomon error correction is effective at dealing with
    noise that occurs in bursts. These algorithms have played an important role
    in telecommunications. libcorrect uses a Viterbi algorithm decoder to
    decode convolutional codes.

    libcorrect should be a drop-in, BSD-licensed substitute for libfec, which
    offers similar functionality under the LGPL-license.
  dev_url: https://github.com/quiet/libcorrect

extra:
  recipe-maintainers:
    - petrushy
    - ryanvolz
