{% set name = "libao" %}
{% set version = "1.2.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://gitlab.xiph.org/xiph/{{ name }}/-/archive/{{ version }}/{{ name }}-{{ version }}.tar.gz
  sha256: df8a6d0e238feeccb26a783e778716fb41a801536fe7b6fce068e313c0e2bf4d

build:
  number: 0
  run_exports:
    - {{ pin_subpackage('libao', max_pin='x.x') }}

requirements:
  build:
    - {{ compiler('c') }}
    - make  # [not win]
  host:
    - alsa-lib  # [linux]
    - pulseaudio  # [linux]

test:
  commands:
    # verify that headers get installed
    {% set headers = [
        "ao.h",
        "os_types.h",
        "plugin.h",
    ] %}
    {% for header in headers %}
    - test -f $PREFIX/include/ao/{{ header }}  # [not win]
    - if not exist %PREFIX%\\Library\\include\\ao\\{{ header }} exit 1  # [win]
    {% endfor %}

    # verify that libraries get installed
    - test -f $PREFIX/lib/libao${SHLIB_EXT}  # [not win]
    - if not exist %PREFIX%\\Library\\bin\\ao.dll exit 1  # [win]
    - if not exist %PREFIX%\\Library\\lib\\ao.lib exit 1  # [win]

    # verify that plugins get installed
    - test -f $PREFIX/lib/ao/plugins-4/libalsa${SHLIB_EXT}  # [linux]
    - test -f $PREFIX/lib/ao/plugins-4/liboss${SHLIB_EXT}  # [linux]
    - test -f $PREFIX/lib/ao/plugins-4/libpulse${SHLIB_EXT}  # [linux]
    - test -f $PREFIX/lib/ao/plugins-4/libmacosx${SHLIB_EXT}  # [osx]
    - if not exist %PREFIX%\\Library\\lib\\ao\\plugins-4\\wmm.lib  # [win]

about:
  home: https://gitlab.xiph.org/xiph/libao
  license: GPL-2.0-or-later
  license_family: GPL
  license_file: COPYING
  summary: 'A Cross-platform Audio Library'
  description: |
    Libao is a cross-platform audio library that allows programs to output
    audio using a simple API on a wide variety of platforms.
  dev_url: https://gitlab.xiph.org/xiph/libao

extra:
  recipe-maintainers:
    - ryanvolz
